import {
	taxAlertDiscordDeliveryStatusEnum,
	taxAlertSeverityEnum,
	taxAlertStatusEnum,
	taxAssessmentLines,
	taxAssessmentScopeEnum,
	taxAssessments,
	taxAssessmentStatusEnum,
	taxAuditLog,
	taxBillStatusEnum,
	taxBillSyncEvents,
	taxCorporationBillingConfigs,
	taxCorporationExclusions,
	taxDiscrepancies,
	taxExportFormatEnum,
	taxExportFrequencyEnum,
	taxExportSchedules,
	taxExports,
	taxExportStatusEnum,
	taxLedgerEntries,
	taxMemberContributionFinalizedRollups,
	taxMemberContributionProjectionRollups,
	taxMemberSummaryVersions,
	taxNotificationDestinations,
	taxPeriods,
	taxPeriodStatusEnum,
	taxRuleGroupAttachments,
	taxRuleGroups,
	taxRuleSets,
	taxSyncCheckpoints,
} from './schema'

/**
 * Migration schema for corporation-tax owned objects only.
 *
 * IMPORTANT:
 * - Do not include cross-domain read-only tables here (e.g. managed_corporations).
 * - Runtime schema may include external tables for typed reads, but migration schema must not.
 */
export {
	taxAlertDiscordDeliveryStatusEnum,
	taxAlertSeverityEnum,
	taxAlertStatusEnum,
	taxAssessmentLines,
	taxAssessmentScopeEnum,
	taxAssessments,
	taxAssessmentStatusEnum,
	taxAuditLog,
	taxBillStatusEnum,
	taxBillSyncEvents,
	taxCorporationBillingConfigs,
	taxCorporationExclusions,
	taxDiscrepancies,
	taxExportFormatEnum,
	taxExportFrequencyEnum,
	taxExportSchedules,
	taxExports,
	taxExportStatusEnum,
	taxLedgerEntries,
	taxMemberContributionFinalizedRollups,
	taxMemberContributionProjectionRollups,
	taxMemberSummaryVersions,
	taxNotificationDestinations,
	taxPeriods,
	taxPeriodStatusEnum,
	taxRuleGroupAttachments,
	taxRuleGroups,
	taxRuleSets,
	taxSyncCheckpoints,
}
