import { EVETIME_PROGRAMMATIC_COMMAND } from './evetime'
import { HOW_PROGRAMMATIC_COMMAND } from './how'
import { MARKET_PROGRAMMATIC_COMMAND } from './market'
import { PING_SLOW_PROGRAMMATIC_COMMAND } from './ping-slow'
import { SRPFLEET_PROGRAMMATIC_COMMAND } from './srpfleet'
import {
	DISCORD_JOIN_PROGRAMMATIC_COMMAND,
	DISCORD_LEAVE_PROGRAMMATIC_COMMAND,
	DISCORD_PART_PROGRAMMATIC_COMMAND,
	DISCORD_ROLES_PROGRAMMATIC_COMMAND,
} from './temporary-roles'

import type { ProgrammaticCommandDefinition } from './types'

export { EVETIME_PROGRAMMATIC_COMMAND } from './evetime'
export { HOW_PROGRAMMATIC_COMMAND } from './how'
export { MARKET_PROGRAMMATIC_COMMAND } from './market'
export { PING_SLOW_PROGRAMMATIC_COMMAND } from './ping-slow'
export { SRPFLEET_PROGRAMMATIC_COMMAND } from './srpfleet'
export {
	DISCORD_JOIN_PROGRAMMATIC_COMMAND,
	DISCORD_LEAVE_PROGRAMMATIC_COMMAND,
	DISCORD_PART_PROGRAMMATIC_COMMAND,
	DISCORD_ROLES_PROGRAMMATIC_COMMAND,
} from './temporary-roles'
export type { DeferralMode, ProgrammaticCommandDefinition } from './types'

export const PROGRAMMATIC_COMMAND_DEFINITIONS: ProgrammaticCommandDefinition[] = [
	EVETIME_PROGRAMMATIC_COMMAND,
	HOW_PROGRAMMATIC_COMMAND,
	MARKET_PROGRAMMATIC_COMMAND,
	PING_SLOW_PROGRAMMATIC_COMMAND,
	SRPFLEET_PROGRAMMATIC_COMMAND,
	DISCORD_JOIN_PROGRAMMATIC_COMMAND,
	DISCORD_PART_PROGRAMMATIC_COMMAND,
	DISCORD_LEAVE_PROGRAMMATIC_COMMAND,
	DISCORD_ROLES_PROGRAMMATIC_COMMAND,
]

export const programmaticCommandDefinitionByName = new Map(
	PROGRAMMATIC_COMMAND_DEFINITIONS.map((definition) => [definition.name, definition])
)
